---
# roles/base/tasks/main.yml
#
- name: Ensure base apt update/upgrade
  apt:
    update_cache: True
    cache_valid_time: 3600
    upgrade: safe
  become: True

- name: Ensure base apt packages are installed
  apt:
    name: "{{ default_apt_list }}" # roles/base/defaults/main.yml
  become: True

    #- name: Create a virtual environment
    #  command:
    #    cmd: python3 -m venv /home/ubuntu/llm-the-alta3-way/venv
    #  args:
    #    creates: /home/ubuntu/llm-the-alta3-way/venv

- name: Ensure base pip packages are installed in the virtual environment
  pip:
    name: "{{ default_pip_list }}"
    virtualenv: /home/ubuntu/llm-the-alta3-way/venv
    virtualenv_python: python3

- name: Create llm directory structure
  file: 
    path: "{{ item }}"
    state: directory
  loop:
   - "{{ llm_dir }}"          # group_vars/all.yml
   - "{{ llm_bin_dir }}"      # group_vars/all.yml
   - "{{ llm_git_dir }}"      # group_vars/all.yml
   - "{{ llm_model_dir }}"    # group_vars/all.yml
   - "{{ llm_prompt_dir }}"   # group_vars/all.yml
   - "{{ llm_dataset_dir }}"  # group_vars/all.yml

- name: Deploy bashrc
  copy:
    src: "files/bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc"

- name: Deploy source files
  synchronize:
    src: "{{ item.src }}/"
    dest: "{{ item.dest }}/"
  loop:
  - src: "{{ src_prompt_dir }}/"
    dest: "{{ llm_prompt_dir }}/"
  - src: "{{ src_model_dir }}/"
    dest: "{{ llm_model_dir }}/"
