---
- name: Setup base playbook (default)
  import_playbook: ../../ansible/default.yml

- name: Install Llama2 70B Orca 200k for use with llama.cpp
  hosts: all
  vars:
    model_dir: "{{ llm_model_dir }}/Llama-2-70B-Orca-200k"
    model_list: "model-min.list"
    llama_dir: "{{ llm_git_dir }}/llama.cpp"

  tasks:
    - name: Verify variables
      debug: 
        msg:
         - "llama_dir: {{ llama_dir }}"
         - "model_dir: {{ model_dir }}"
         - "model_list: {{ model_list }}"


    - name: Create Model dir
      file:
        path: "{{ model_dir }}"
        state: directory

    - name: Verify deployed model file list
      file:
        path: "{{ model_dir }}/{{ model_list }}"
        state: file

    - name: Fetch Model Parameters
      script:
        cmd: "fetch-min.sh"
        chdir: "{{ model_dir }}"

    - name: Example usage
      debug:
        msg: 
          - "see {{ model_dir }}/README.md for example usage"
            # TODO delete after README.md written
            #  - "cd {{ model_dir }} && ./unsplit"
            #  - "cd {{ llama_dir }}"
            #  - "./main -ngl <LAYERS> --threads 14 --model {{ model_dir }}/<model>.gguf --file {{ llm_prompt_dir }}/instruct/ansible.txt"
            #
