---
# roles/webui/tasks/main.yml

# Modified version of 
#  - https://github.com/oobabooga/text-generation-webui#manual-installation-using-conda
# Changes:
#  - No conda
#  - Virtualenv
- name: Verify variables
  debug: 
    msg:
     - "webui_dir: {{ webui_dir }}"       # role invocation
     - "webui_repo: {{ webui_repo }}"     # roles/webui/defaults/main.yml
     - "webui_branch: {{ webui_branch }}" # roles/webui/defaults/main.yml

- name: Clone webui
  git:
    repo: "{{ webui_repo }}"   
    dest: "{{ webui_dir }}"     
    single_branch: True
    version: "{{ webui_branch }}"
    # ignore local changes after first checkout
    update: False 

- name: Setup webui venv
  pip:
    requirements: "requirements.txt"
    chdir: "{{ webui_dir }}"
    virtualenv: "{{ webui_dir }}/venv"
    virtualenv_command: "python3 -m venv"

- name: Setup torch for webui
  vars:
    extra_index_url: "https://download.pytorch.org/whl/rocm5.4.2" 
  pip:
    name: 
    - torch
    - torchvision
    - torchaudio
    extra_args: "--extra-index-url={{ extra_index_url }}"
    virtualenv: "{{ webui_dir }}/venv"
    virtualenv_command: "python3 -m venv"

- name: Create symbolic link for Llama-2-70B-Orca-200k
  file:
    src: "/home/paperspace/llm/model/Llama-2-70B-Orca-200k/model/"
    dest: "~/llm/git/webui/models/Llama-2-70B-Orca-200k"
    state: link

- name: Create symbolic link for falcon-40b-instruct
  file:
    src: "/home/paperspace/llm/model/falcon-40b-instruct/model/"
    dest: "~/llm/git/webui/models/falcon-40b-instruct"
    state: link

- name: Create symbolic link for orca_mini_v3_13b
  file:
    src: "/home/paperspace/llm/model/orca_mini_v3_13b/model/"
    dest: "~/llm/git/webui/models/orca_mini_v3_13b"
    state: link

- name: Deploy systemd service for webui
  template:
    src: "webui.service.j2"
    dest: "/etc/systemd/system/webui.service"
  become: True

- name: Start systemd service for webui
  systemd:
    name: "webui.service"
    daemon_reload: True
    enabled: True
    state: "started"
  become: True
