---
# roles/base/tasks/main.yml

- name: Ensure base apt packages are installed
  package:
    name: "{{ default_apt_list }}" # group_vars/all.yml
  become: True

- name: Install cli llm tools from pip
  pip:
    name: 
      - "{{ pip_llm }}"  # group_vars/all.yml
      - "{{ pip_ttok }}" # group_vars/all.yml

- name: Create llm directory structure
  file: 
    path: "{{ item }}"
    state: directory
  loop:
   - "{{ llm_dir }}"          # group_vars/all.yml
   - "{{ llm_bin_dir }}"      # group_vars/all.yml
   - "{{ llm_git_dir }}"      # group_vars/all.yml
   - "{{ llm_model_dir }}"    # group_vars/all.yml
   - "{{ llm_prompt_dir }}"   # group_vars/all.yml
   - "{{ llm_dataset_dir }}"  # group_vars/all.yml

- name: Deploy bashrc
  copy:
    src: "files/bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc"

- name: Deploy source files
  synchronize:
    src: "{{ src_prompt_dir }}/"
    dest: "{{ llm_prompt_dir }}/"

