---
- name: Setup base playbook (default)
  import_playbook: ../../ansible/default.yml

- name: Install Orca mini v3 13B GGML for use with llama.cpp
  hosts: all
  vars:
    model_dir: "{{ llm_model_dir }}/orca_mini_v3_13b"
    aria2_list: "model-min.list"
    llama_dir: "{{ llm_git_dir }}/llama.cpp"

  roles:
    - name: Install llama.cpp
      role: ../../ansible/roles/llama.cpp
      vars: 
        llama_dir: "{{ llm_git_dir }}/llama.cpp"

  tasks:
    - name: Verify variables
      debug: 
        msg:
         - "llama_dir: {{ llama_dir }}"
         - "src_model_dir: {{ src_model_dir }}"
         - "model_dir: {{ model_dir }}"
         - "aria2_list: {{ aria2_list }}"

    - name: Create Model dir
      file:
        path: "{{ model_dir }}"
        state: directory

    - name: Verify deployed modle file list
      file:
        path: "{{ model_dir }}/{{ aria2_list }}"
        state: file

    - name: Fetch Model Parameters
      shell:
        script: "fetch-min.sh"
        chdir: "{{ model_dir }}"

    - name: Example usage
      debug:
        msg: 
          - "see {{ model_dir }}/README.md for example usage"
