---
# roles/langchain/tasks/main.yml

- name: Verify variables
  debug: 
    msg:
     - "langchain_dir: {{ langchain_dir }}"       # role invocation
     - "langchain_repo: {{ langchain_repo }}"     # roles/langchain/defaults/main.yml
     - "langchain_branch: {{ langchain_branch }}" # roles/langchain/defaults/main.yml

- name: Clone langchain
  git:
    repo: "{{ langchain_repo }}"   
    dest: "{{ langchain_dir }}"     
    single_branch: True
    version: "{{ langchain_branch }}"
    # ignore local changes after first checkout
    update: False 

# equivilant to:
#  - python3 -m venv {{ langchain_dir }}/venv 
#  - source {{ langchain_dir }}/venv/bin/activate
#  - python3 -m pip install {{ langchain_requirements }}
- name: Setup langchain venv
  pip:
    name: "{{ langchain_requirements }}"
    virtualenv: "{{ langchain_dir }}/venv"
    virtualenv_command: "python3 -m venv"

- name: Setup llama-cpp-python cuBLAS wheel install
  vars:
    extra_index_url: "https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu117"
  pip:
    name: "llama-cpp-python"
    extra_args: "--prefer-binary --extra-index-url={{ extra_index_url }}"
    virtualenv: "{{ langchain_dir }}/venv"
    virtualenv_command: "python3 -m venv"
