---
- name: Default install
  hosts: all
  vars:
    golang_install_dir: '/usr/local/go'

  roles:
  - name: Base Install
    role: base

  - name: Golang Install
    role: golang

  - name: hfdownloader Install (requires golang)
    role: hfdownloader
    vars: 
      hfdownloader_dir: "{{ llm_git_dir }}/hfdownloader"  # group_vars/all.yml
      install_dir: "{{ llm_bin_dir }}"                    # group_vars/all.yml
      golang_cc: '{{ golang_install_dir }}/bin/go'

  - name: Install llama.cpp
    role: llama.cpp
    vars: 
      llama_dir: "{{ llm_git_dir }}/llama.cpp"

  - name: Install lit-gpt
    role: lit-gpt
    vars: 
      lit_dir: "{{ llm_git_dir }}/lit-gpt"

  - name: Install webui
    role: webui
    vars: 
      webui_dir: "{{ llm_git_dir }}/webui"
