---
# roles/caddy/tasks/main.yml

- name: Verify variables
  debug:
    msg:
      - "caddy_url: {{ caddy_url }}"     # roles/caddy/defaults/main.yml  
      - "caddy_file: {{ caddy_file }}"   # roles/caddy/defaults/main.yml  

- name: Get Caddy reverse proxy binary
  get_url:
    url: "{{ caddy_url }}/{{ caddy_file }}"
    dest: "/tmp/{{ caddy_file }}"

- name: Untar binary
  unarchive:
    src: "/tmp/{{ caddy_file }}"
    dest: "/usr/local/bin"
    remote_src: yes
  become: yes

- name: Set binary permissions
  file:
    path: "/usr/local/bin/caddy"
    mode: "0755"
  become: yes
